### ISSUE TITLE
ps3netsrv: Add support for encrypted (3k3y / Redump) PS3 isos

### ISSUE THREAD

**Issue by SpaceAgeHero** [aldostools/webMAN-MOD#225] opened 2019-06-27 09:17 UTC
Dear aldo,

please add support for encrypted (3k3y / Redump) PS3 isos to ps3netsrv.
This was already achieved earlier by NvrBst over at redump.org.
Source Code and description can be found in this thread:
http://forum.redump.org/topic/14472/ps3netsrv-modified-for-encrypted-3k3yredump-isos/
Perhaps his changes can just be merged in?

Thanks!

**Comment by aldostools** [comment] 2019-06-27 11:15
Thank you for the link... I merged that fork with mine... I don't have 3k3y isos to test if it works.
[ps3netsrv_20190627.zip](https://github.com/aldostools/webMAN-MOD/files/3334320/ps3netsrv_20190627.zip)

Only the binary of ps3netsrv for win32 is included.

EDIT:
This is a revised version 
[ps3netsrv_20190627.1.zip](https://github.com/aldostools/webMAN-MOD/files/3335564/ps3netsrv_20190627.1.zip), it's only the SRC without binaries of ps3netsrv.

**Comment by SpaceAgeHero** [comment] 2019-06-27 19:22
I've just tested the binary from ps3netsrv_20190627.zip with an encrypted .iso + .dkey.
It works fine. Thanks alot.

**Comment by aldostools** [comment] 2019-06-27 19:23
Can you compile 20190627.1 and test it too? I can't compile it ATM.

**Comment by fabriciofoxx** [comment] 2019-06-27 19:43
I'm trying to compile a linux version but gives me a error:

<builtin>: recipe for target 'File.o' failed
make: *** [File.o] Error 1

**Comment by SpaceAgeHero** [comment] 2019-06-27 19:47
I can't compile I'm afraid. I don't have the environment ready.
I'll be happy to test the next binary tomorrow if you can provide one.

**Comment by aldostools** [comment] 2019-06-27 19:48
> I'm trying to compile a linux version but gives me a error:
> 
> : recipe for target 'File.o' failed
> make: *** [File.o] Error 1

did you replace ./polarssl-1.3.2/library/libpolarssl.a with the linux version?

You can find 3 versions of that library it in ./polarssl-1.3.2/bin for different platforms

> I can't compile I'm afraid. I don't have the environment ready.
> I'll be happy to test the next binary tomorrow if you can provide one.

Ok, I will compile it for Win32 tonight when I get back home.

**Comment by aldostools** [comment] 2019-06-28 02:16
[ps3netsrv_20190628.zip](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.24/ps3netsrv_20190628.zip) includes ps3netsrv for Win32 + SRC

Updated the project with new flag NOSSL (uncomment it in Makefile to build the project without support for encrypted ps3isos)

**Comment by SpaceAgeHero** [comment] 2019-06-28 18:35
With ps3netsrv_merge_drives.exe everything is working fine. ps3netsrv.exe ignores /PS3ISO/ if there is content in /GAMES/ but that is obviously intended?

**Comment by aldostools** [comment] 2019-06-28 18:50
That is not the intended behavior. ps3netsrv_merge_drives.exe basically scans the folders in the directory passed as argument, then it shows the content of these folders for all attached drives.

e.g. C:\SHARE\PS3ISO will show also the isos in D:\PS3ISO, E:\PS3ISO, ... Z:\PS3ISO

**Comment by SpaceAgeHero** [comment] 2019-07-01 06:55
Okay. So did I do something wrong or could it be a bug?

**Comment by aldostools** [comment] 2019-07-01 12:27
Sorry but I don't have idea why you got that behavior... I checked the code and I couldn't find anything wrong.

For the moment, ignore ps3netsrv_merge_drives.exe and use only **ps3netsrv.exe**

**Closed as completed** 2019-07-03 14:04 UTC
Labels: enhancement

**Comment by SpaceAgeHero** [comment] 2020-04-02 17:53
Dear @aldostools 
can this on-the-fly decryption be integrated directly into webMAN itself, so that locally stored & encrypted ISOs can be launched?
I have a use case for this because I can no longer host my ps3netsrv.
Thanks

**Comment by aldostools** [comment] 2020-04-02 18:42
Short answer: No.

The function is already there and theoretically it can be added to the code of webMAN.
However, the resources of memory and processing on the PS3 are more limited than in a PC.

Remember that webMAN is a plugin that is running in background all the time. While more features are added to the plugin, more memory is consumed and more potential issues arise with games and other system functions.
