### ISSUE TITLE
Synology Intel ps3netsrv_20170310.zip

### ISSUE THREAD

**Issue by Viper911** [aldostools/webMAN-MOD#102] opened 2017-06-19 13:51 UTC
Do you have a ps3netsrv_20170310.zip version that can run on a intel based Synology NAS device?

**Comment by aldostools** [comment] 2017-06-19 17:03
The files that I have are the ones available in the repository.

You can try asking in psx-place.com/forums

**Comment by masterzorag** [comment] 2017-06-20 08:18
@Viper911, I can try to build latest ps3netsrv for your model, but need target infos:
can you log in and check at least /proc/cpuinfo?
We have already done for Mips (big and little) at #36 ...

**Comment by Viper911** [comment] 2017-06-20 12:53
It’s a sinology 1817+.    I did notice on GIT in the “webMAN-MOD<https://github.com/aldostools/webMAN-MOD>/_Projects_<https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_>/ps3netsrv<https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv>/bins<https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins>/old<https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/old>/SynologyDS1512_INTEL/” folder there is an Intel compiled file there, just not sure if that is the latest version or an older version of ps3netsrv.  It shows up as part of webMAN MOD 1.46.00<https://github.com/aldostools/webMAN-MOD/commit/daae514418f1d2f401bad3adf327b0d717d504cb> (or if it would work with my model.

Hardware Specifications

CPU

CPU Model

Intel Atom C2538

CPU Architecture

64-bit

CPU Frequency

Quad Core 2.4 GHz

Hardware Encryption Engine (AES-NI)

Memory

System Memory

2/8 GB DDR3

Memory Module Pre-installed

2GB (1 x 2GB) / 8GB (2 x 4GB)

Total Memory Slots

2

Memory Expandable up to

16 GB (8 GB x 2)

**Comment by masterzorag** [comment] 2017-06-20 16:11
@Viper911 the ps3netsrv is changed a little [here](https://github.com/aldostools/webMAN-MOD/commit/732abf14428853553b562873a2711b9a7aa15148#diff-a285caf4f4484942ca9c459680cb74bf) from 1.46.00
your CPU seems x86 little endian, supporting 64bit instructions, first test: try the old one and post the result;
if it runs, I can recompile the updated version with file/build info from the old working one.

**Comment by Viper911** [comment] 2017-06-20 19:49
Yup, old one works and is running on the synology and games load up.  Just old version it sounds like..

**Comment by kawalskiz** [comment] 2017-07-15 19:25
@masterzorag, after update my DS416Play to v6.1.2, PS3Netsrv (extracted Intel version from webMAN-MOD) doesn´t work. In previous versions it was working. Perhaps, can you compile a new version of ps3netsrv?

**Comment by masterzorag** [comment] 2017-07-16 08:37
I see [here](https://www.synology.com/en-global/products/DS416play#spec) it's a Celeron N3060, with 64bit support:
which is the old working ps3netsrv version and any info on the running OS?
dmesg content?

The v6.1.2 firmware image is just updated by [two other versions](https://www.synology.com/en-global/releaseNote/DS416play), the updater into the v6.1.3 fw image is this:
```sh
updater: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), for GNU/Linux 2.6.32, statically linked, stripped, with debug_info
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - GNU
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
```
also, the kernel (zImage) does not boot on a i686 asking for an x86_64 CPU so, this NAS runs a 64bit OS.

Also, your CPU support VT-x, it can potentially virtualize windows XP without problems 😆

**Comment by masterzorag** [comment] 2017-07-16 10:14
```sh
blackbox ps3netsrv # file ps3netsrv 
ps3netsrv: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, stripped, with debug_info
blackbox ps3netsrv # ./ps3netsrv /Archive 
ps3netsrv build 20170106 (mod by aldostools)
Path: /Archive

Waiting for client...
Connection from 127.0.0.1
client_thread(), client @0x7f8f6fd90da8
BE16-LE
command received: 3131
BE16-LE
BE16-LE
Unknown command received: 3131
finalize_client()

^C
```
Compiled for 64bit, generic
```sh
blackbox ps3netsrv # echo "" | gcc -v -E - 2>&1 | grep cc1
/usr/libexec/gcc/x86_64-pc-linux-gnu/5.4.0/cc1 -E -quiet -v - -mtune=generic -march=x86-64 -fstack-protector-strong
```
@kawalskiz, [ps3netsrv-x86_64-dbg-static.zip](https://github.com/aldostools/webMAN-MOD/files/1150944/ps3netsrv-x86_64-dbg-static.zip) should work, @Viper911 can you try it too?

**Comment by kawalskiz** [comment] 2017-07-16 11:31
@masterzorag, sorry for the delay (and for my english too)

- First of all, thanks for your time and the new compiled version.
- The last working ps3netsrv version was the one in "webMAN-MOD-1.47.04 sources" (webMAN-MOD-1.47.04.zip\webMAN-MOD-1.47.04\_Projects_\ps3netsrv\bins\old\SynologyDS1512_INTEL). It showed me one error ("libstdc++.so.6: no version information available"), but with nohup I could run it, and I saw the games in Multiman. 
- Past thursday, after updating to v.6.1.2 ¿update 2? (I´ll try to verify exactly this night), the same commands didn´t run ps3netsrv (ps | grep ps3netsrv). 
- I see there is a new DSM version. I´ll update it and i will try with old and new version.
- What do you need about dmesg? Any command or file in particular? As you can see i´m not a Linux expert.

**Comment by kawalskiz** [comment] 2017-07-17 15:53
@masterzorag, I have made some tests
- old version of ps3netsrv (from webMAN-MOD-1.47.04) started to fail when I upgrade to DSM 6.1.2-15132 Update 1. Previously I can started it whith nohup ("nohup /volume2/ps3netsrv/ps3netsrv /volume2/games"). If I tried to start it directly ("/volume2/ps3netsrv/ps3netsrv /volume2/games") it gave me one error ("libstdc++.so.6: no version information available")
- Last night I have upgraded my NAS to DSM 6.1.3-15152, but I have the same problem with old version
- Your new version shows this error:
```
ps3netsrv build 20170106 (mod by aldostools)
Path: /volume2/ps3install

Whitelist: C0A80000-C0A8FFFF
Error in bind: 98
Error in initialization.

```
Can I help you to debug the software (execute some commands or extract some information / files)?
Thanks

**Comment by masterzorag** [comment] 2017-07-18 08:32
- First, do not use `nohup` until you are getting ps3netsrv to run;
It will fork the process and if it's running will keep the socket busy, then new process will spot the error in binding.
Also, in the case on any error you will not notice errors due you fork in the background!
(To exit, just kill the server with CTRL-C.)
- If you have forked the process, kill the old ps3netsrv instance by getting pid_number `ps -a | grep ps3netsrv` and then `kill -s KILL pid_number`

On finalize_client() socket connection enter the `TIME_WAIT` state, read [more on this](https://hea-www.harvard.edu/~fine/Tech/addrinuse.html)
On my OS, TIME_WAIT state then times out in a minute, closing the socket; `netstat -ntp` will lists connection states, check if you have that command in your NAS OS

**Comment by kawalskiz** [comment] 2017-07-20 09:18
Hello @masterzorag,

After cleaning some scripts and rebooting the system, the new version of ps3netsrv is running ok. It does not display the error "libstdc++.so.6: no version information available" like old version, so I don´t need to lauchn it with "nohup" command. Everything runs smoothly.

Thank you very much for yor help!!

**Comment by Viper911** [comment] 2017-07-29 10:50
@masterzorag  was out of town, but will try it.  I just updated to the latest DSM as well, so hopefully this version will work.  

@kawalskiz what "cleaning of scripts" did you have to do?

**Comment by kawalskiz** [comment] 2017-07-31 17:46
Hello, I launch the program with a script when the NAS is booting. i forget to "clean" this script (I used "nohup" command), so during the tests (I run manually the new version) I found that the program can listen correctly (Error in bind: 98) because the old version was disturbing :-(.

**Comment by Azzhoe** [comment] 2018-06-23 19:56
Hello, could someone please help me. I have a Synology 1512+ NAS running on DSM 6.2 (Intel Atom Processor). I am trying to setup ps3netserv on my NAS. I installed docker and added the repository to use ps3netserv from within docker. But I am not sure how to set up my PS3 game folders and where to place my games? I have /volume1/Contents/Ps3/GAMES/ is this correct?

UPDATE: I'm having no luck getting this version of ps3netsrv to work. It keeps showing 'waiting for clients' in the log.

@masterzorag Could you please compile the latest version of ps3netserv for my Synology NAS 1512+ (Running DSM 6.2/Intel Atom) if you don't mind.

My CPU is a Dual Core Intel Atom (2.13GHz) D2700 / Arch: Cedarview

**Comment by Joonie86** [comment] 2019-05-17 00:35
Since there's no further feedback for the past 11 months and the issue is not maintained by us. Closing this issue.

**Closed as completed by Joonie86** 2019-05-17 00:35 UTC
Labels: help wanted
