### ISSUE TITLE
3d Bluray Iso mounted with webman mod loses picture/sound

### ISSUE THREAD

**Issue by Foojoo** [aldostools/webMAN-MOD#11] opened 2016-09-10 18:48 UTC
This is a bug that has been in older builds of webman before. (and fixed)  I was playing a mounted 3d bluray iso with webman mod 1.43.35. and it seems like when the ps3 fan turns on, the picture is "kicked" out of 3d mode, and/or the sound drops out.  I disabled webman and tried mounting the bluray iso with IRISMAN v3.50.10, and I was able to play the full movie without any issues.
  I was playing the files from a 128 gb Pny usb stick formatted ntfs.  The bluray was in the BDISO folder.  The same thing also happened with webman mod 1.43.33.

**Comment by aldostools** [comment] 2016-09-10 18:58
Thank you for your report. Unfortunately I can't afford a 3D tv to test, so I need some feedback to be able to fix the issue.

Could you try the following?
1- Please install the vanilla version from deank and test if the issue still happens.
This test is verify if the issue was caused by some of the hundreds of changes in webMAN MOD, or if it has been like that all the time.

2- Please try different settings for the fan controller:
a) Mount the ISO with wMM and set the fan to manual mode and test if the issue persists.
b) Mount the ISO with wMM and set the fan to dynamic mode and test the issue again.
c) Mount the ISO with wMM, untick Enable dynamic fan control in /setup.ps3 and test again.

Then report back how it behaves in each scenario. Please reboot before test each setting.

**Comment by Foojoo** [comment] 2016-09-11 02:43
Alright, I've just finished the testing -
Webman_mod
-Manual Mode (35% fan) Picture reverts to 2d after 20-5 minutes
-Dynamic mode -This is the mode I was in originally.  I had the fan set to operate at 70 degrees.  The picture reverts to 2d every 5 minutes or so, and the sound drops out.
-Dynamic fan control unticked - The picture remained 3d for the entire movie.  I didn't watch the entire movie,  so I can''t say for certain that there were no sound dropouts, but I did watch for 20 minutes, and the sound was fine.

Original Webman 1.43
I only tested the Dynamic mode, there were no problems.

**Comment by aldostools** [comment] 2016-09-11 03:25
Thank you for your feedback. It is interesting to know that the Dynamic mode works fine on Original 1.43.

The algorithm for dynamic fan on webMAN MOD is almost identical to the original.
So I guess the issue could be caused by the extra processing of other tasks, like the polling of the WM_REQUEST file.

Could you test the Dynamic mode with the Lite edition?
If this behaves properly, then I'd say that the issue is caused by the WM_REQUEST file and I could fix it.

If the issue still happens with the Lite edition, then I suggest you to use the Original webMAN until a solution could be found or disable the dynamic fan temporarily using L3+R2+START while you watch the movies (although it is not suggested if your console is getting hot easily)

Also download & install the current pkg on github (even if it has the same version number of the plugin installed on your console). It's just to be sure that you're testing with the latest build.

**Comment by Foojoo** [comment] 2016-09-11 21:12
I've just finished some more testing.  I installed the sprx from github directly, (previous version was the update package)  
Both the full and lite versions have the same problem.  The audio/picture dropouts definitely happen when the fan is engaged.  I also played a few mkv files with Movian, and there were dropouts when the temperature rose and the fan was engaging.  
  Not sure if this helps at all, but I found an old forum thread from psx-scene.  Deank released version 1.28 of regular webman, and it fixed the same problems I was having.  Versions prior to 1.28 had the same dropouts  when the fan was engaging.

**Comment by aldostools** [comment] 2016-09-11 22:25
Thank you for your feedback. I compared 1.28 and 1.27 and there are many changes between these versions. I couldn't identify which exactly fixed the issue. Also webMAN MOD is using the latest code, so the fix in 1.28 should be already included.

If the issue happens in manual mode and in the lite edition, I don't have a clue what could be the cause of the problem.

In manual mode, the fan speed is constant and the thread that controls the fan doesn't make any change to the fan. And the lite edition has minimal extra processing (e.g. it doesn't polls the wm_request_file).

My suggestion is try setting the fan to manual at 40-45% to watch the movies. Maybe keeping the console very cool the fan is not engaged and hopefully the issue would happen less often.

Or simply use the official release of webMAN until a solution can be found in the future.

**Comment by Joonie86** [comment] 2019-05-16 07:30
Closing old cases that have no further feedback. please use the latest version of wMM and report us

**Closed as completed by Joonie86** 2019-05-16 07:30 UTC
