### ISSUE TITLE
After exit of multiman , when mounting ps1 game system will freeze

### ISSUE THREAD

**Issue by dragonkni** [aldostools/webMAN-MOD#63] opened 2017-02-24 10:58 UTC
This problem is since webMAN MOD 1.46.00. Probably becouse new webman mount game without the webbrowser_plugin.

After exit multiman (and playing game mount by multiman) after that when mount ps1  game in xmb by webman system freeze. Also mounting by browser works fine.

Also in version 1.47 most ps1 game will not start and freeze system.

**Comment by jonaaa20** [comment] 2017-02-24 11:57
There's a workaround for this:

1. After exiting Multiman, go to webMAN
2. Press on Refresh XML (or something like that, i don't remember it well xD)
3. Mount a game?

**Comment by shawly** [comment] 2017-02-24 14:24
I can confirm the PS1 game freezing within version 1.47. #62

**Comment by jonaaa20** [comment] 2017-02-24 14:30
Yes, it's a known issue...

**Comment by aldostools** [comment] 2017-02-27 01:39
Please try with 1.47.01... wMM 1.46.xx and 1.47.00 had an issue computing the LBA from the CUE.

**Comment by dragonkni** [comment] 2017-03-04 20:22
Unfortunately similar problem still exist in 1.47.01. After mounting Tekken Tag Tournament via Multiman and after exit to xmb cant mount ps1 game via Webman. This time there is no freezing but clicking on ps1 image disc do nothing. Ty aldstools for your support.

**Comment by shawly** [comment] 2017-03-04 20:36
Same thing for the NTSC-U version of Silent Hill, even on a fresh system with REBUG 4.81.2 it won't work, same on my old system. Disabling Cobra and then loading Silent Hill via Multiman works fine, but not via WebMAN, I had this problem since WebMAN 1.45.x. The PAL version of Silent Hill works fine though..

**Comment by Joonie86** [comment] 2019-05-16 07:32
Closing old cases that have no further feedback. please use the latest version of wMM and report us

**Closed as completed by Joonie86** 2019-05-16 07:32 UTC
