### ISSUE TITLE
webMAN hungs console when I try to install "ROMS_PKG_Launcher.pkg"

### ISSUE THREAD

**Issue by mlody95pl** [aldostools/webMAN-MOD#299] opened 2020-01-27 18:21 UTC
webMAN hungs console when I try to install "ROMS_PKG_Launcher.pkg" from addons menu:

![image](https://user-images.githubusercontent.com/4082647/73201636-be4ed480-4139-11ea-9752-2c67b280e74c.png)

Browser quits and console hungs when animation transition is shown, like on photo:

![image](https://user-images.githubusercontent.com/4082647/73201596-a414f680-4139-11ea-883e-a8bca13a7dd4.png)

Only power off and on again helps, but still I can't install this...

**Comment by aldostools** [comment] 2020-01-27 18:35
IIRC this issue occurs only on 4.85.

I haven't had the chance to check it due I'm on Rebug 4.84.2 REX and lately don't have free time.

**Comment by gosseux** [comment] 2020-01-28 22:22
if I remember correctly, webman mod  freeze the console with every .pkg installation.  No matter if you use the ps3 browser or  a computer. 
The workaround is to install via the ps3 package installer.

**Comment by mlody95pl** [comment] 2020-01-30 14:56
Any chance for fix this ?

**Comment by mlody95pl** [comment] 2020-02-21 18:43
@aldotools pls fix this issue or add addons as separate files on github

**Comment by aldostools** [comment] 2020-02-21 19:36
As I mentioned above, the issue is with 4.85. It works fine on Rebug 4.84

I have uploaded the addons to the release
https://github.com/aldostools/webMAN-MOD/releases/tag/1.47.26

Or can download the addons direclty from the repository
https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/updater/pkgfiles/USRDIR/addons

**Comment by mlody95pl** [comment] 2020-02-21 21:46
Sorry I didn't saw those files :)

**Comment by aldostools** [comment] 2020-04-19 00:50
Fixed in 1.47.27

**Closed as completed by aldostools** 2020-04-19 00:50 UTC
