### ISSUE TITLE
Dynamic fan control is activated when temperature is too high

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#13] opened 2016-09-17 12:04 UTC
Even if Dynamic fan control and temperature warnings are disabled, when the PS3 teperature is 80-85º the fan kicks at 100% making a lot of noise, and from then Dynamic fan control is kept active until you turn off the PS3 (because the option appears to be kept off in webman configuration)

With irisman, you can set fan control  to syscon and the PS3 will work same as running an OFW. The 100% fan speed never happens using irisman (webman disabled). I don't know if this a feature or a bug, but syscon fan control should be always available and not overridden by Dynamic fan control.

Thanks

**Comment by aldostools** [comment] 2016-09-17 15:43
Thank you for your feedback.

When the option "Enable dynamic fan control" is not marked in /setup.ps3, the fan control is set to syscon mode.

Regarding the fan kicking to 100% even if the temperature warning is disabled, is a safety feature to prevent damages to your console if the temperature is too high. The warning setting refers only to the popup displayed on the screen.

You prefer the silence (with the risk of cause damages to your console), you can disable the dynamic fan control or edit the source code to change the hard coded limit of 85ºC.

**Comment by 444nonymous** [comment] 2016-09-17 16:47
Just to be clear I have both "dynamic fan control" and "temperature warning" disabled. This should be syscon only mode and yet dynamic fan control kicks in when temperature is high. It does not happen with irisman, syscon mode works just like syscon.

Here is the thing, I never fried a PS3 with syscon. I think syscon automatically updates the fan frequency and even shuts down the PS3 to prevent damage if it's too hot (never happened to me).

If it's a hot day and I'm playing a demanding game, temperatures can peak at some point but they tend to go back. Suddenly kicking the fan to 100% with all the noise forces you to stop playing and turning off the PS3, it's far from ideal. The intention is really good and It should be there, but only when selected.

I think the default behavior should be to only let syscon take care when selected (like irisman). Maybe rewriting the options with a clear message about what they do and possible problems should help, or maybe you could change "Disable temperature warning" to also "Disable temperature warning / overheating protection" which would disable both warnings and fan kicking at 100%.

**Comment by aldostools** [comment] 2016-09-17 19:56
Well the safety was intended for protection of the user assets...

Anyway I changed the behavior, so now the fan speed increase only if the warning is enabled.
https://github.com/aldostools/webMAN-MOD/releases/edit/1.43.35

**Comment by 444nonymous** [comment] 2016-09-20 14:57
I've tested this and syscon only mode is working fine.

**Comment by aldostools** [comment] 2016-09-20 21:25
Thank you for the feedback. Closing.

**Closed as completed by aldostools** 2016-09-20 21:25 UTC
