### ISSUE TITLE
Webman 4.84.2, nothing works

### ISSUE THREAD

**Issue by cthog** [aldostools/webMAN-MOD#176] opened 2019-03-30 19:08 UTC
Hi All,

I've got a disappointed 8 year old checking on my progress every 5 minutes.  PS3 updated to Rebug 4.84.2.  Installed latest webman Mod.  Running ps3netsrv from a docker, has always been solid, so I'm pretty sure no issue there.  Now when I load Webman, *sometimes* it will see the games, sometimes it comes up empty (0 games), depending on the reboot.  Whether it sees the games or not, nothing loads.  I restored PS3 to defaults and formatted the drive before setting everything up (it was cathartic), so no old settings should be messing things up.   Any ideas where to start troubleshooting?

--Chris

**Comment by Joonie86** [comment] 2019-05-16 07:50
We can't reproduce this issue. Please try the latest wMM and report back to us. Closing this issue since no other feedback was reported.

**Closed as completed by Joonie86** 2019-05-16 07:50 UTC
