### ISSUE TITLE
webMAN not ready iusse

### ISSUE THREAD

**Issue by jakdarklight** [aldostools/webMAN-MOD#231] opened 2019-07-01 08:14 UTC
I'm on .24 version (last) and every time i turn on my ps3 webmanmod is not ready, i have to reinstall webman mod. also ftp is down when webman mod is not ready. plz fix it

**Comment by Joonie86** [comment] 2019-07-01 08:29
Do you have boot_plugins.txt on your USB? If so, please remove it

**Comment by jakdarklight** [comment] 2019-07-01 08:36
no i don't use any USB

**Comment by jakdarklight** [comment] 2019-07-01 09:56
i've also tried to:
-uninstall and reinstall webmanmod;
-restore default setting of ps3 system;
-reinstall cfw;

but problem still here.. fan control of webmanmod work, but if i try to run a game or enter webman options a notification said me: webMAN not ready
FTP don't work only if webman not ready.
I had this problem also in previous releases, but now every time i turn on i have to reinstall webmanmod...plz i really need a help

**Comment by aldostools** [comment] 2019-07-01 12:38
Please check that your network connection is enabled... the "not ready" message is shown by [wm_proxy](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/wm_proxy/main.c#L178) when it cannot connect to the http server.

Also try deleting **/dev_hdd0/tmp/wm_config.bin** and reboot to restore the default settings, in case you have changed some setting that could be preventing the connections.

Remove any additional plugin in /dev_hdd0/boot_plugins.txt, like psnpatch.sprx or sen enabler or sman.sprx. These plugins are network related and could be interfering with webMAN.

If the problem persists, try re-installing a different edition (e.g. lite edition), a previous build or uninstall wMM completely and test if sMAN or webMAN vanilla also have the issue and report back.

**Comment by jakdarklight** [comment] 2019-07-01 13:33
I don't use any additional plugin, boot_plugins.txt only contains the string for webmanmod.
For now the problem happens randomly, but often.
sometimes I start the console and webman works, sometimes not (webman not ready)
I tried deleting /dev_hdd0/tmp/wm_config.bin and reboot to restore the default settings, and at the beginning it works, but then randomly it doesn't work again.

However, this problem was always occurred also in previous versions ( i remember from .09).

PS: the network console setting is set with a static IP, maybe that's why it has problems?

**Comment by aldostools** [comment] 2019-07-01 13:51
Static IP is the suggested configuration.

Maybe you're trying to perform actions before the plugin is ready like the error says. For instance, webMAN could be still scanning for content while you're trying to mount a game. Try checking the option "**Disable content scan on startup**" in **/setup.ps3**

If you have  remote servers checked and the ps3netsrv is offline, uncheck the options. These options tend to cause connection issues when the ps3netsrv are offline because webMAN keeps trying to connect to the server a long period (about 1 minute).

Also remove any delay (e.g. in boot_init.txt or autoexec.bat), reduce the waits for USB if you use that option and uncheck any USB device that you don't use to speedup the scanning.

Other than this, I'm out idea of what could be producing your error. I rarely see it (practically never).

**Comment by jakdarklight** [comment] 2019-07-01 14:14
disabled content scan on startup and unchecked remote servers , cause i don't use ps3netsrv.
for now everything seems ok, but I'll let you know if I have problems again (since the problem always presents itself in a very random way).

(ps: I don't think it is still the case to close the post as I don't know if the problem has actually been solved or not yet.. do you agree?)

**Comment by aldostools** [comment] 2019-07-01 14:20
Feel free to keep it open if the issue is not solved. 
I think for now you can close it and re-open it if the problem re-appears and need further attention.

**Comment by LouisGarry** [comment] 2019-07-07 13:23
Can you play PS3 using a wireless stick? usually it is a result of damage to the wifi / bluetooth module.

**Comment by aldostools** [comment] 2019-07-09 12:34
Closing the issue due there is not further feedback.

**Closed as completed by aldostools** 2019-07-09 12:34 UTC
Labels: help wanted
