### ISSUE TITLE
Launching ROM from XMB to RetroArch CE at 720p hangs

### ISSUE THREAD

**Issue by opheliagh** [aldostools/webMAN-MOD#714] opened 2022-05-20 16:51 UTC
Greetings,

If I prepare a ROM for loading via the WebMAN Games folder and launch it directly from the XMB into RetroArch CE in 720p, the console hangs with garbled ROM graphics. I then hit the power button on the PS3 and wait for it to power off.

Launching from XMB into a ROM at 1080p runs perfectly. Launching RetroArch CE first at 720p and loading a ROM from within works perfectly.

I have noticed this in 1.47.41, 1.47.38  and 1.47.37.

Cheers,
ophelia

**Comment by aldostools** [comment] 2022-05-20 17:02
Dear ophelia,
Thank you for your report. I have confirmed your issue. I will investigate if I can find a setting that works for all resolutions.

If I can't a proper setting, I will update the plugin to change the configuration file to match the current screen resolution.

**Comment by aldostools** [comment] 2022-05-21 01:00
@opheliagh A new update has been uploaded with a small change to the RetroArch config files.

I tested 720p and 1080p with the updated config and it isn't freezing. Please update to validate if the issue is solved on your side. Thank you.

**Comment by opheliagh** [comment] 2022-05-21 01:06
@aldostools I just updated via XMB and it works perfectly with 720p and 1080p now. Thank you!

**Comment by aldostools** [comment] 2022-05-21 01:08
Excellent! Thank you for your feedback. I'm closing this issue.

**Closed as completed by aldostools** 2022-05-21 01:08 UTC
