### ISSUE TITLE
Cannot access webMAN Setup through XMB

### ISSUE THREAD

**Issue by mabdullahsari** [aldostools/webMAN-MOD#147] opened 2018-07-31 13:47 UTC
So, when I try accessing the setup that launches a browser window through XMB, it does not work.
Instead, I'm presented with an empty column that does not load anything at all. I tried updating webMAN to the latest revision, but with no avail. Tried re-installing after removing every piece of WM that was left in the HDD, still the same. I tried it on another PS3, also presented with an empty column.

I can access it using the VSH menu, but would rather prefer this way.
A glitch of some sort?

(using Rebug 4.82.2 REX if that's of importance)

**Comment by JordanTheDev** [comment] 2018-10-18 02:16
I've been having the same issue for years. If I find a fix ill let you know. Also if you happen to figure it out would you shoot me a DM. Thanks.

**Comment by Joonie86** [comment] 2019-05-16 07:26
since the case's old no further feedback was received. closing this one. We can't reproduce this issue either.

**Closed as completed by Joonie86** 2019-05-16 07:26 UTC

**Comment by DBLobster** [comment] 2022-03-31 03:27
Same Bug, empty column browser.

webMAN MOD 1.47.38
PS3 2501A
4.88.2 EVILNAT (COBRA 8.3) CFW

**Comment by aldostools** [comment] 2022-03-31 07:08
There was a build with a bug that created a corrupted mygames.xml which breaks the display of webMAN Games menu.

The bug has been corrected and the installer was replaced. Download the installer again from brewology or from the release page in GitHub.

**Comment by DBLobster** [comment] 2022-04-02 09:58
Thank you.
When I use browser from LAN IP, is OK, yesterday.
I will update today.

20220407 edited
Sorry. I enable PS3 LAN porxy, but my proxy server limit LAN <-> LAN access. So, not webMAN issue.
