### ISSUE TITLE
Cover not showing in html or xml view for title "MRTC00003"

### ISSUE THREAD

**Issue by Grntrenchman** [aldostools/webMAN-MOD#167] opened 2018-12-10 10:17 UTC
I have this game, Final Fantasy 13, with serial BLUS30416, but the sfo reads MRTC00003.
I have a MRTC00003.JPG and BLUS30416.JPG in with the rest of my covers in multiman folder, but neither loads.
Filename is FINAL FANTASY XIII  [MRTC00003].iso
Every other cover is fine.

**Comment by aldostools** [comment] 2018-12-10 13:09
Did you try copying the cover also to /PS3ISO as "FINAL FANTASY XIII [MRTC00003].JPG" (or .jpg in lower case)?

**Comment by Grntrenchman** [comment] 2018-12-10 17:54
I have a .PNG of each iso's icon0 with the iso, named (iso).PNG, not (iso).iso.PNG, and webman does not load these. I have all my games on PC, shared over PS3netsrv. I haven't been able to get webman to pull any covers or icons over nethost. I will try putting the cover jpg in with the isos.

Edit:
I put the cover as indicated, and it did not load.

**Comment by Grntrenchman** [comment] 2018-12-10 19:35
I'm doing some more testing. I put the Iso-matched cover in the wmtmp folder, refreshed xml, and we have a cover... so it matches the filename that way correctly, but I believe we're encountering a second problem where neither multiman nor webman are getting covers for network isos when it indexes them. I see that webman is generating ICON0 pngs matched to the iso names in wmtmp for games that have been run, but it isn't getting them from where the iso file is, instead from inside the iso.

So webman isn't fetching the images for the isos from ps3netsrv.

Edit:
After removing the image from wmtmp, refreshing removed the cover, but mounting it copied it back over from net, and now it shows, so your method works, but requires mounting once.

Still some edge-case problem with the file lookup for the multiman cover. Any way to troubleshoot that? Otherwise, this works, and I'll just copy them straight into wmtmp for problem games from now on. easy enough to FTP *.jpg and not overwrite.

Also, that webman doesn't check for iso-matched covers on network games when generating xml.
I guess have it check for and copy over from the iso folder if it fails to find a cover through multiman when scanning for content?

So two issues.

I also found that webman HTML file browser sometimes fails to list a whole directory.
for instance my covers directory has about 8k files, but when i browse there in the webpage, it shows only 4k files, and it seems random, not to a certain letter or size range.

**Comment by Joonie86** [comment] 2019-05-17 00:27
So your saying that you have 8,000 covers and it only shows 4,000 covers sometimes? 
we cannot afford that amount of games and hard to reproduce such issues. 

Since there's no further feedback for the latest version of wMM for the past 5 months, we are closing this issue.

**Closed as completed by Joonie86** 2019-05-17 00:27 UTC
