### ISSUE TITLE
PS3Netsrv not working via Retronas (NOT A RETRONAS ISSUE)

### ISSUE THREAD

**Issue by davedoc1984** [aldostools/webMAN-MOD#627] opened 2022-03-08 12:19 UTC
I have previously been able to mount and launch PS3 games using RetroNAS and PS3Netsrv with no issues whatsoever. 

In recent times, this has stopped working. RetroNAS logs show the below when you try and select a NET PS3 Game from webMAN-MOD

The same happens in mm-CM too. RetroNAS devs confirm this is a PS3netsrv issue and not because of RetroNAS.

![image](https://user-images.githubusercontent.com/97349996/157236868-01301a6e-e032-4379-a636-7b2337d90a12.png)

**Comment by aldostools** [comment] 2022-03-08 13:12
Try early versions to find the last working build.

**Comment by davedoc1984** [comment] 2022-03-08 13:34
How do I go about doing that? How can I install an Earlier Version in RetroNAS?

**Comment by aldostools** [comment] 2022-03-08 18:12
I haven't used a RetroNAS, I don't know what you did to run ps3netsrv on it.

In [releases](https://github.com/aldostools/webMAN-MOD/releases) on each previous releases you have a zip that includes ps3netsrv source code. You can compile the project or ask to the devs that released it for RetroNAS that compile it for you.

**Comment by sairuk** [comment] 2022-03-30 22:07
RetroNAS (targets raspios or deb11, uses bash/ansible/jinja) in regards to ps3netsrv specfically
1. ansible configures system
1. pulls latest src archive of ps3netsrv
1. compiles on the device (meson/ninja)
1. sets up a systemd service 
1. runs as an unpriv user

were not doing anything funky on our end with the execution of ps3netsrv

systemd ExecStart entry
```
/opt/retronas/bin/ps3netsrv /data/retronas/ps3/ps3netsrv
```
Our related issue/files for reference
- [thread](https://github.com/danmons/retronas/issues/129)
- [installer template](https://github.com/danmons/retronas/blob/main/ansible/templates/install_ps3netsrv/install_ps3netsrv.sh.j2)
- [systemd template](https://github.com/danmons/retronas/blob/main/ansible/templates/install_ps3netsrv/ps3netsrv.service.j2)

I've asked op to give me a title that this specifically happens with to test now that I have a working 20220330 setup to see if I can dig out some more info.

**Comment by sairuk** [comment] 2022-04-21 05:23
An update on this one, this actually looks to be an underlying OS issue. We've done a bunch of testing and haven't been able to reproduce this with any of our recommended OS. We've found issues with raspiOS with larger storage which could be the cause of these kernel dumps.

 I'd suggest from here and the RetroNAS side we can close both @aldostools

**Comment by aldostools** [comment] 2022-04-21 13:28
@sairuk Thank you for your feedback. I will close the issue. If there is more information in the future the issue can be reopened.

**Closed as completed by aldostools** 2022-04-21 13:28 UTC
