### ISSUE TITLE
Bug webman mod 1.47.20

### ISSUE THREAD

**Issue by Croi100** [aldostools/webMAN-MOD#193] opened 2019-05-11 15:46 UTC
when you reset your ps3 and you reinstall webman mod after the reset the webman mod configuration menu page is bug and i reset my ps3 fat and slim to do something the same bug on both
![Screenshot_20190511_174408_com android gallery3d](https://user-images.githubusercontent.com/50524375/57571933-86212d80-7414-11e9-83b2-8d3d1cf26cd2.jpg)

**Comment by Croi100** [comment] 2019-05-11 15:50
same on pc browser

**Comment by aldostools** [comment] 2019-05-11 15:51
Sorry, but I don't see bug in the picture... Could you describe it a little more, please?

**Comment by Croi100** [comment] 2019-05-11 15:56
it's just not the original webman mod  page that's what i meant sry

**Comment by Croi100** [comment] 2019-05-11 16:00
She's just not as usual and it's weird right?

**Comment by aldostools** [comment] 2019-05-11 16:06
Uncheck the option sMAN GUI and SAVE! It should look as usual.

**Comment by Croi100** [comment] 2019-05-11 16:07
I am gonna try 😊

**Comment by Croi100** [comment] 2019-05-11 16:15
Thanks a lot and just to know it's normal that when I load a game on multiman and I unload it and then when I load the game on my webman my ps3 freeze

**Comment by aldostools** [comment] 2019-05-11 17:35
No, it's not normal... This issue occurs because webMAN MOD redirects a system file to the plugin wm_proxy.sprx to be able to receive the command from XMB.

However multiMAN clears all the existing redirections, including the wm_proxy, which causes the freeze.

This issue should be resolved in webMAN MOD 1.47.20. It restore the redirections when it detects that you returned to XMB.

**Comment by Croi100** [comment] 2019-05-11 17:48
My bad u fix it nice a other bug when u install like gta 5 in multiman and u go to XMB after that u load the game (gta5) with webman mod ps3 freeze

**Comment by Croi100** [comment] 2019-05-11 17:50
But it's not serious

**Comment by Croi100** [comment] 2019-05-12 07:14
Do I need to close this

**Comment by aldostools** [comment] 2019-05-12 14:05
Close it when your issue is fixed.
Currently I cannot reproduce your bug with multiMAN. The issue that I could find so far was fixed.

**Comment by Croi100** [comment] 2019-05-12 20:25
Is that normal when i disable sycall with triangle+r2 and after press select + start I cant see the fan real speed

**Comment by Croi100** [comment] 2019-05-12 20:26
Is written 24% but sound like 60

**Comment by aldostools** [comment] 2019-05-12 21:36
No, it's not normal. I first need to reproduce and confirm it, then investigate why it happens.

**Comment by Croi100** [comment] 2019-05-13 06:18
Ok

**Comment by Croi100** [comment] 2019-05-13 07:59
Do u have the bug too?

**Comment by aldostools** [comment] 2019-05-13 12:55
I have been busy working in PS3HEN and MAMBA payloads.
I will work on webMAN when I have some free time. I'm at work right now.

**Comment by Croi100** [comment] 2019-05-13 13:22
O sryy

**Comment by Croi100** [comment] 2019-05-13 19:12
Just so you know the Bug fan I have it on 47.20 but not on 47.15

**Comment by Croi100** [comment] 2019-05-15 10:54
If u want to fix this bug fan I think is only on 47.20

**Comment by Croi100** [comment] 2019-05-15 14:44
It's on 19 too

**Comment by Croi100** [comment] 2019-05-16 06:32
Hi my friend I have just install webman mod on my ps3 fat and at every start she make a fan noise like 100% fan

**Comment by Croi100** [comment] 2019-05-16 06:33
?

**Comment by Joonie86** [comment] 2019-05-16 07:19
> Hi my friend I have just install webman mod on my ps3 fat and at every start she make a fan noise like 100% fan

Delete wmconfig, and set your desired fan speed. closing this issue.

**Closed as completed by Joonie86** 2019-05-16 07:19 UTC

**Comment by Croi100** [comment] 2019-05-16 08:17
Thx😊

**Comment by Croi100** [comment] 2019-05-16 08:33
But why I have only this on my fat

**Comment by Joonie86** [comment] 2019-05-16 09:45
If your PS3 model is CECH"L" then this is perfectly normal behavior, it goes 100% at start up but goes down shortly after

**Comment by Croi100** [comment] 2019-05-16 10:20
Yep

**Comment by Croi100** [comment] 2019-05-16 10:21
Because she freeze at shutdown or just the fan make noise for nothing

**Comment by Croi100** [comment] 2019-05-16 10:21
?

**Comment by Croi100** [comment] 2019-05-16 10:32
I just deleted the 2 wmconfig in tmp and the wmconfig.bin just keep reinstall and my fan still make noise

**Comment by Croi100** [comment] 2019-05-16 10:32
I think I am not gonna use webman mod's fan  on my fat and use syscon mod xD

**Comment by Croi100** [comment] 2019-05-16 10:33
I am sad
