### ISSUE TITLE
XMB Freezes when selecting a PS3 game from PS3NetServ

### ISSUE THREAD

**Issue by Jektt** [aldostools/webMAN-MOD#386] opened 2020-07-25 13:39 UTC
As soon as I select any PS3 game in the GAME folder where I have PS3NetServ hosting, the XMB freezes. It gets as far as showing a popup in the top right with the game title and path, but never mounts it.

I am running PS3NetServ on Windows, 4.86 CFW PS3, running an unpacked game in the GAMES folder.
Tried
-Deleted all other managers and packages (no Multiman, Irisman, or any other packages)
-Removed and reinstalled latest wMM + apps
-Fresh PS3NetServ folder
-Tried Rebug and Ferrox firmwares. (4.86)
-Turning off Windows Defender and firewall

Working for other people? Any ideas?

**Comment by aldostools** [comment] 2020-07-25 14:20
Please try downloading again the latest wMM (I uploaded a new commit last night), 
Also try with 1.47.28 and report back the results,

**Comment by Jektt** [comment] 2020-07-25 14:32
1.47.28 caused the same crash as 1.47.29.

I will try other versions from further back.

**Comment by aldostools** [comment] 2020-07-25 14:42
Thank you for your feedback. Could you verify that Cobra is enabled and wMM is running? (use SELECT+START to check both).

Please check if your issue is only mounting through XMB or if it also happens mounting through the web browser (locally and remote from PC or smartphone).

Try detaching any USB device and remove any other sprx in boot_plugins.txt, with the intention of isolate the cause of the issue.

Also try with different game types: PSXISO, PS3ISO and GAMES. This is with the intention of know if only certain type of games cause the freeze.

**Comment by Jektt** [comment] 2020-07-26 01:44
Cobra and wMM are definitely running.
webMAN 1.47.29 MOD
4.86 CEX Cobra 8.2 (NTFS) [Full]

Mounting GAMES through XMB, local through the browser or remotely from the browser all cause the same freeze immeditaly after the /net0/GAMES/Infamous (BCU98119) popup (or whatever unpacked game I try).

Tried a PS3ISO also on the network, and I do get the load message and no freeze, but no icon to actually start the game appears.. strange?

There are no plugins in boot_plugins.txt except the FTP server.

No USB drive is plugged in.

**Comment by Nimrod-002** [comment] 2020-07-26 19:52
i m having the same ptroblem, cant mount folders through ps3netsrv. tried using older ps3netsrv, changing port number, selecting a net hosted game on xmb shows the notification but doesnt load the disk also PS3 NET SERVER doesnt show 'building virtual ISO' text, so whatever is broken is not sending the command to pc to build virtual ISO

**Comment by aldostools** [comment] 2020-07-26 19:55
I found the cause. A new fix will be released later today.

**Comment by shadowblade227** [comment] 2020-07-26 20:15
Oh, such a good timing. 
Last three hours trying to deal with this problem (but PS3ISO completely worked for me), helped downgrade to 1.47.27.

**Comment by aldostools** [comment] 2020-07-26 22:29
@shadowblade227 Thank you for your feedback and my apologies for the time that you invested in this error.

The issue should be solved in build 1.47.30
https://github.com/aldostools/webMAN-MOD/releases

**Comment by shadowblade227** [comment] 2020-07-27 00:19
@aldostools Yes, everything seems to be working fine now. 
Thank you for prompt support.

**Comment by aldostools** [comment] 2020-07-27 00:26
Thank you everyone for your reports. Closing the issue.

**Closed as completed by aldostools** 2020-07-27 00:26 UTC
