### ISSUE TITLE
XMB issue

### ISSUE THREAD

**Issue by JordanTheDev** [aldostools/webMAN-MOD#154] opened 2018-10-05 01:08 UTC
I've had this issue for YEARS and it really had bothered me. The first time I used webman it came with Rebug built in. It worked great! The next time there was a required update for the PS3 system to get online. I did so and it broke Webman. I did the usual steps that you've recommended. Toggling Cobra, Enable disable in rebug toolbox/update rebug toolbox. I even uninstalled every component in FTP that has to do with webman. Then reinstalled MULTIPLE times. So here's my issue. When I install webman the xmb icon shows up for webman above the BD icon like it should but when I click it there's nothing in the folder. no games no setting nothing. But I would love to just use it from the xmb. I've been using the R2+L2 command to get to my games then pressing Triangle to get to the SETUP.ps3 I've checked all my setting in there. I ONLY boot games from internal hdd not USB or external. I am on the latest webman mod. when I install I hold L1 Yes Ive refreshed XML and HTML. webMAN MOD v1.47.09. I've provided screenshots of the XMB.
![20181004_204920](https://user-images.githubusercontent.com/12107336/46510888-748dfc80-c819-11e8-956b-1b5814d01410.jpg)
![20181004_204941](https://user-images.githubusercontent.com/12107336/46510889-748dfc80-c819-11e8-9c4f-751c8d3d78ee.jpg)

**Comment by Joonie86** [comment] 2019-05-16 07:49
We can't reproduce this issue. Please try the latest wMM and report back to us. Closing this issue since no other feedback was reported.

**Closed as completed by Joonie86** 2019-05-16 07:49 UTC
