### ISSUE TITLE
Only 1 PSX game is shown in PSXISO

### ISSUE THREAD

**Issue by vinhtq115** [aldostools/webMAN-MOD#341] opened 2020-04-30 15:27 UTC
On my PS3, webMan only show 1 game in Playstation 1 games list. I'm using external HDD (NTFS) and here is the folder structure:
`Folder PATH listing
Volume serial number is XXXX-XXXX
F:.
├───NES

├───PS3ISO

└───PSXISO

    ├───Crash Bandicoot [NTSC-U] [SCUS-94900]

    │       Crash Bandicoot [NTSC-U] [SCUS-94900].bin

    │       Crash Bandicoot [NTSC-U] [SCUS-94900].cue

    │

    └───Crash Team Racing [U] [SCUS-94426]

            CTR - Crash Team Racing (USA).bin

            CTR - Crash Team Racing (USA).cue`

Webman only shows Crash Bandicoot in Playstation 1 games list. This also happened when there are 2 Metal Gear Solid bin/cue and Mortal Kombat. Only MGS disc 1 is shown instead of all 3.

Could you investigate this? Thank you.

**Comment by kam821** [comment] 2020-04-30 17:08
Try keeping folder and bin/cue names the same and/or refresh XML (game list) once again.

Also I think it may be related:
https://github.com/aldostools/webMAN-MOD/issues/324

I noticed that many problems are caused by additional covers, but even without it, there are issues in XML Refreshing, for example Webman-MOD adds only one PS1 game available on ps3netsrv server by refresh.

**Comment by aldostools** [comment] 2020-04-30 23:04
I have refactored the prepNTFS module in webMAN MOD and updated the prepISO tool.

The issue should be fixed. Maybe the issue #324 too,

**Comment by kam821** [comment] 2020-05-01 19:48
@aldostools 
Unfortunately, I don't remember what it looked like before recent changes, but now Webman-MOD loads PS1 games on ps3netsrv at once, but only one remote cover (also in ps3netsrv, same filename as game) per XML Refresh.

ps3netsrv output:

First XML Refresh attempt:
> Connection from X.X.X.X
> open /mnt/datastore/ps3netsrv/PSXISO/Crash Bandicoot (USA) [SCUS94900].jpg

Second XML Refresh:
> Connection from X.X.X.X
> open /mnt/datastore/ps3netsrv/PSXISO/Tekken 3 (USA) [SLUS00402].jpg

etc.

Webman-MOD/PrepISO Release: https://github.com/aldostools/webMAN-MOD/commit/04c6305c10c2052e08cc9518b8d57360a8ab4749

**Comment by aldostools** [comment] 2020-05-02 18:54
Remote covers issue fixed in commit eebafd8

NTFS scanning issue fixed 2 days ago in commit bd0281e6fa6714cebfff63223389be5422e4b84e

**Closed as completed by aldostools** 2020-05-02 18:54 UTC
